services:
  mysql:
    image: mysql:8.4.4
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yuntas
      MYSQL_DATABASE: yuntasproducciones
      MYSQL_USER: yuntasproducciones
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
